### PR TITLE
Create new certificate if none exists

### LINKED ISSUE #39: Doesn't create a certificate for the first time
Web job will renew a certificate that already exists, but doesn't create a certificate for the first time like the letsencrypt extension.

This limits it's usefulness, especially for multi-tenanted apps where new domains are added on a regular basis.

### PR DESCRIPTION
**Pull request by jaykay-design**
Fixes #39

### CODE REVIEW

**Comment by ohadschn** [comment]
Thank you, this looks good, will try and merge it for the next release

**Comment by ohadschn** [comment]
It looks like the code in this PR does something similar to what `LetsEncrypt.Azure.Core.CertificateManager::RenewCertificate` does, except the latter seems to be more robust (look at the comments explaining why `client.Certificates` wasn't used), and I wouldn't want the webjob to be the weakest link: https://github.com/sjkp/letsencrypt-siteextension/blob/8e758579b21b0dac5269337e30ac88b629818889/LetsEncrypt.SiteExtension.Core/CertificateManager.cs#L146

In addition, the code in this PR simply checks whether an LE cert is associated with one of the SSL bindings, but no hostname validation takes place, so if I have multiple bindings it could be looking at an irrelevant one.

I think a better approach here would be to submit a PR for the https://github.com/sjkp/letsencrypt-siteextension repo that resolves this: https://github.com/sjkp/letsencrypt-siteextension/issues/188. We could then use `AddOrRenewCertificate` in the webjob and be done with it.

**Comment by ohadschn** [comment]
Looking at this some more, I think I have an even better solution. I simply look at the list of renewed certs returned `RenewCertificate` and see if they covered the currently requested hosts. If not, I call `AddCertificate`. Here's how it looks, will test and if works as expected, will merge:

```cs
var renewed = await manager.RenewCertificate(false, renewalParams.RenewXNumberOfDaysBeforeExpiration);

var missingHostNames = acmeConfig.Hostnames.Except(renewed.SelectMany(cim => cim.AllDnsIdentifiers), StringComparer.OrdinalIgnoreCase).ToArray();
if (missingHostNames.Length == 0)
{
	Trace.TraceInformation("All done - cert renewal covered all requested host names");
	return;
}

Trace.TraceInformation("Renewal missed the following host names, adding new certificate: {0}", String.Join(", ", missingHostNames));
await manager.AddCertificate();
Trace.TraceInformation("SSL cert added successfully to '{0}'", renewalParams.WebApp);
```

**Comment by ohadschn** [comment]
Actually scratch that, it won't work because I can't differentiate between a host name without an SSL binding and a hostname with an SSL binding whose cert isn't about to expire. So back to resolving https://github.com/sjkp/letsencrypt-siteextension/issues/188 (or maybe just expose the logic for getting certs).

**Comment by ohadschn** [comment]
So I got impatient and took the needed code from `letsencrypt-siteextension` and modified it.
Closing in favor of https://github.com/ohadschn/letsencrypt-webapp-renewer/pull/76.

**Comment by jaykay-design** [comment]
> In addition, the code in this PR simply checks whether an LE cert is associated with one of the SSL bindings, but no hostname validation takes place, so if I have multiple bindings it could be looking at an irrelevant one (`foo.com` has a LE cert but `bar.com`, which is the one we might want to renew, does not).

I'm not sure this is how LE certificates work. 
In above case `bar.com` would be added to the certificate as an alternate name of `foo.com` when the certificate of `foo.com` is renewed. No need to add a new certificate. 
I imagine one could use LE to create a separate certificate for each domain of an app but the way this project handles configuration that will never be the case. 
So my conclusion is that only checking if the app has an LE certificate should handle any domains being added or removed from the app correctly.

**Comment by ohadschn** [comment]
> I imagine one could use LE to create a separate certificate for each domain of an app but the way this project handles configuration that will never be the case.

Not true, I can think of several ways this could happen:
1. You use multiple instances `letsencrypt-webapp-renewer` (multiple web apps with the webjob installed).
1. You use the groups feature, created expressly for this purpose: https://github.com/ohadschn/letsencrypt-webapp-renewer#multiple-certificates-for-a-single-site.
1.  You change domains (only specify `foo.com` and then only specify `bar.com`).

**Comment by jaykay-design** [comment]
> 
> 
> > I imagine one could use LE to create a separate certificate for each domain of an app but the way this project handles configuration that will never be the case.
> 
> Not true, I can think of several ways this could happen:
> 
>     1. You use multiple instances `letsencrypt-webapp-renewer` (multiple web apps with the webjob installed).
> 
>     2. You use the groups feature, created expressly for this purpose: https://github.com/ohadschn/letsencrypt-webapp-renewer#multiple-certificates-for-a-single-site.
> 
>     3. You change domains (only specify `foo.com` and then only specify `bar.com`).

Totally embarrassing I did not see that :-) Thanks!

**Comment by ohadschn** [comment]
No worries, and thank you again for the PR - while I didn't take this exact code, it pointed me in exactly in the right direction to resolve an important issue which I previously thought I was blocked on 👍

**Pull request closed without merging**
